spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: utf-8