spring:
  datasource:
    url: jdbc:mysql://172.29.186.104:3306/mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: utf-8
  messages:
    basename: i18n/messages